### ISSUE TITLE
standardize file extensions

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#15]
Proposal:
+ raw binary data must have the extension `X.dat`
+ csv files must have the extensions `X.csv`
+ yaml metadata files must have the same name as the reference dataset but with the extension `X.meta.yaml`, this is a change from `X.meta`
+ Metadata about the entries should be in a file called `meta.yaml`

Why:
+ Clarity and simplicity. Listing the contents of a directory will tell you the dataset types in addition to their names.
+ Enforcing `.csv` for CSV files may help with using third party tools
+ Enforcing `.meta.yaml` both makes it clear the file is metadata AND that the format is YAML, an editor will open in the correct mode. Choosing `.meta.yaml` over `.yaml` is because other non-bark data may stored in `.yaml` files. YAML suits Bark's philosophy well, so other YAML uses are likely.
+ The extension can be dropped from the name of the DataSet, ie dataset.name could be "eeg" instead of "eeg.dat".
+ `filetype` is no longer needed as a metadata attribute.

@gfetterman Thoughts?

**Comment by gfetterman** [comment]
A few thoughts:
1. I prefer having file extensions be a strong suggestion rather than a requirement. I agree that it would allow easy perusal of dataset types via `ls`, but I don't think that advantage is large enough to be worth restricting users' naming choices.
   * And keep in mind that the mapping from file extension to dataset type isn't necessarily 1-to-1. As you remind me whenever I bring dataset type inference up, there's no reason you couldn't keep a sampled dataset in a `.csv`.
2. No objection to changing metadata filename suffixes to `[whatever].meta.yaml`. Your point about cluing text editors in to the type of the files is a good one.
   * And I **definitely** agree that a plain `.yaml` extension should not be interpreted as a metadata file.
3. I can't think of a problem with dropping the file extension from the `Dataset.name`, but what's the advantage?
   * Perhaps one argument against it: the extension _is_ conceptually part of a file's name, and a dataset is a file, so `Dataset.name` should contain the full name of the file.

**Comment by kylerbrown** [comment]
Thanks for your feedback. Good points.

Let's say we have file called `hvc.dat`. Is it too awkward to have the metafile be `hvc.dat.meta.yaml`? That's a 13 character extension! what about `hvc.dat.m.yml`? That saves us four characters at least. There is a readability cost for both for long names and abbreviations... not sure what the sweet spot is.

**Comment by gfetterman** [comment]
`.meta.yaml` is long, but it's probably not the end of the world.

And `.m.yml` has the disadvantage of possibly being misinterpreted as a `.m` file of some kind.

Let's say I have a weak preference for keeping it as `.meta.yaml`.
